# Generated by Django 4.0.2 on 2022-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoveCartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('cartoonName', models.CharField(max_length=15)),
                ('cartoonImg', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cartoonId', models.IntegerField()),
                ('isLove', models.BooleanField(default=False)),
            ],
        ),
    ]
