# Generated by Django 4.0.2 on 2022-08-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lovecartoon',
            table='lovecartoon',
        ),
    ]
