# Generated by Django 4.0.2 on 2023-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0002_alter_lovecartoon_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonMess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoonId', models.IntegerField()),
                ('cartoonName', models.CharField(max_length=15)),
                ('cartoonImg', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cartoonState', models.IntegerField()),
                ('cartoonTag', models.CharField(max_length=20)),
                ('cartoonAuthor', models.CharField(max_length=15)),
                ('updateTime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cartoonmess',
            },
        ),
    ]
