# Generated by Django 4.0.2 on 2023-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0003_cartoonmess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonmess',
            name='cartoonAuthor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartoonmess',
            name='cartoonImg',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartoonmess',
            name='cartoonName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartoonmess',
            name='cartoonTag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartoonmess',
            name='updateTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lovecartoon',
            name='cartoonName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lovecartoon',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
