# Generated by Django 4.0.2 on 2023-03-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0004_alter_cartoonmess_cartoonauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonmess',
            name='cartoonState',
            field=models.CharField(max_length=30),
        ),
    ]
