# Generated by Django 4.0.2 on 2023-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0005_alter_cartoonmess_cartoonstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonmess',
            name='description',
            field=models.TextField(),
        ),
    ]
