# Generated by Django 4.0.2 on 2023-03-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0006_alter_cartoonmess_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cartoonName', models.CharField(max_length=100)),
                ('cartoonImg', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cartoonId', models.IntegerField()),
                ('readTime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'historycartoon',
            },
        ),
    ]
