# Generated by Django 4.0.2 on 2023-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='supportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essayId', models.IntegerField()),
                ('commentId', models.IntegerField()),
                ('supportAuthor', models.CharField(max_length=200)),
                ('isSupport', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'supportcomment',
            },
        ),
    ]
